version: 2
updates:
  - package-ecosystem: "npm" # Use the appropriate ecosystem (e.g., npm, yarn, pip)
    directory: "/" # Root directory of your project or specify subdirectory
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10