name: "sentinel-scanner"

on: [push]

permissions: "write-all"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  dependencies:
    name: 📦 Dependencies
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - run: npm ci && npm install -g better-npm-audit

  lint:
    name: 🔬 Lint & Format
    runs-on: macos-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - run: npm ci
      - name: 🔬 Lint & Format
        run: npm run lint:check

  audit:
    name: 🛡️ Audit
    runs-on: macos-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - name: 🛡️ Audit
        run: npm run audit

  spell:
    name: 🈸 Spellcheck
    runs-on: macos-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - run: npm ci
      - name: 🈸 Spellcheck
        run: npm run spell:check

  type:
    name: ʦ Typecheck
    runs-on: macos-latest
    needs: [dependencies]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - run: npm ci
      - name: ʦ Typecheck
        run: npm run type:check

  build-and-release:
    name: 🚀 Build & release
    needs: [lint, audit, spell, type]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "npm"
      - run: npm ci
      - name: 🔨 Build
        run: npm run build
      - name: 🚀 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release
